# Generated by Django 5.2.7 on 2025-11-10 19:23

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('refund_number', models.CharField(db_index=True, help_text='Unique identifier for the refund', max_length=20, unique=True, verbose_name='Refund Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the refund', max_length=20, verbose_name='Status')),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('defective_product', 'Defective Product'), ('wrong_item', 'Wrong Item Received'), ('damaged', 'Damaged During Shipping'), ('late_delivery', 'Late Delivery'), ('quality_issue', 'Quality Issue'), ('size_issue', "Size Doesn't Fit"), ('other', 'Other')], help_text='Reason for the refund', max_length=50, verbose_name='Reason')),
                ('reason_description', models.TextField(blank=True, help_text='Detailed description of the refund reason', null=True, verbose_name='Reason Description')),
                ('refund_method', models.CharField(choices=[('original_payment', 'Original Payment Method'), ('store_credit', 'Store Credit'), ('bank_transfer', 'Bank Transfer'), ('gift_card', 'Gift Card')], default='original_payment', help_text='Method used to process the refund', max_length=20, verbose_name='Refund Method')),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Amount requested for refund', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount Requested')),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved for refund', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount Approved')),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually refunded to customer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount Refunded')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the refund was requested', verbose_name='Requested At')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the refund was processed', null=True, verbose_name='Processed At')),
                ('customer_notes', models.TextField(blank=True, help_text='Additional notes from the customer', null=True, verbose_name='Customer Notes')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for staff', null=True, verbose_name='Internal Notes')),
                ('refund_receipt', models.FileField(blank=True, help_text='Refund receipt document', null=True, upload_to='refunds/receipts/', verbose_name='Refund Receipt')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'refunds',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of items to refund', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Refunded')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of refund', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('defective_product', 'Defective Product'), ('wrong_item', 'Wrong Item Received'), ('damaged', 'Damaged During Shipping'), ('late_delivery', 'Late Delivery'), ('quality_issue', 'Quality Issue'), ('size_issue', "Size Doesn't Fit"), ('other', 'Other')], help_text='Reason for refunding this specific item', max_length=50, verbose_name='Item Reason')),
            ],
            options={
                'verbose_name': 'Refund Item',
                'verbose_name_plural': 'Refund Items',
                'db_table': 'refund_items',
            },
        ),
    ]
