# Generated by Django 5.2.7 on 2025-11-10 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('payments', '0002_initial'),
        ('refunds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='customer',
            field=models.ForeignKey(help_text='Customer receiving the refund', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(help_text='Order being refunded', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(help_text='Original payment being refunded', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='order_item',
            field=models.ForeignKey(help_text='Order item being refunded', on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='refund',
            field=models.ForeignKey(help_text='Refund containing this item', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='refunds.refund', verbose_name='Refund'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_number'], name='refunds_refund__a55d04_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'is_deleted'], name='refunds_status_ab47dc_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order', 'status'], name='refunds_order_i_37bade_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['customer', 'status'], name='refunds_custome_61f9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='refunds_payment_908281_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_number', 'is_deleted'], name='refunds_refund__ebd9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'is_deleted', 'requested_at'], name='refunds_status_3dce22_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['customer', 'is_deleted', 'requested_at'], name='refunds_custome_d01eec_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['requested_at', 'status'], name='refunds_request_c38a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['processed_at', 'status'], name='refunds_process_643bac_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['requested_at', 'customer'], name='refunds_request_cb058f_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['is_deleted', 'status', 'requested_at'], name='refunds_is_dele_a8db08_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_method', 'is_deleted', 'status'], name='refunds_refund__4543b7_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'amount_requested'], name='refunds_status_39f43a_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_method', 'status'], name='refunds_refund__6f6f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['is_active', 'is_deleted', 'status'], name='refunds_is_acti_525832_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['reason', 'status', 'is_deleted'], name='refunds_reason_cce6fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_approved__lte', models.F('amount_requested'))), name='approved_amount_lte_requested'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded__lte', models.F('amount_approved'))), name='refunded_amount_lte_approved'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing'])), fields=('order', 'status'), name='unique_pending_refund_per_order'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['refund', 'is_deleted'], name='refund_item_refund__312aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['order_item', 'is_deleted'], name='refund_item_order_i_9e5831_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['quantity', 'unit_price'], name='refund_item_quantit_c9a992_idx'),
        ),
        migrations.AddConstraint(
            model_name='refunditem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('refund', 'order_item'), name='unique_order_item_per_active_refund'),
        ),
    ]
