# Generated by Django 5.2.7 on 2025-11-23 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_orderstatushistory_status_and_more'),
        ('payments', '0003_alter_payment_payment_reference'),
        ('refunds', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['is_deleted'], name='refunds_is_dele_190abc_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['is_active'], name='refunds_is_acti_461289_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['is_deleted', 'is_active'], name='refunds_is_dele_ca8aed_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['date_created', 'is_deleted'], name='refunds_date_cr_dc3d32_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='refunds_is_dele_72d1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='refunds_date_cr_fc6bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['is_deleted'], name='refund_item_is_dele_0d9790_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['is_active'], name='refund_item_is_acti_437a52_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['is_deleted', 'is_active'], name='refund_item_is_dele_ca095f_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['date_created', 'is_deleted'], name='refund_item_date_cr_fde9df_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='refund_item_is_dele_74c67d_idx'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='refund_item_date_cr_342b9b_idx'),
        ),
    ]
