# Generated by Django 5.2.7 on 2025-10-25 16:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('payment_reference', models.CharField(help_text='Unique transaction ID from the payment processor or internal system.', max_length=100, unique=True, verbose_name='Payment Reference')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('currency', models.CharField(default='USD', help_text='Currency code in ISO 4217 format (e.g., USD, EUR, PLN).', max_length=3, verbose_name='Currency')),
                ('method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('PAYPAL', 'PayPal'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='CREDIT_CARD', help_text='Method used for payment.', max_length=30, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the payment.', max_length=20, verbose_name='Payment Status')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when the payment occurred.', verbose_name='Transaction Date')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed (if applicable).', null=True, verbose_name='Confirmed At')),
                ('notes', models.TextField(blank=True, help_text='Optional comments or metadata about the payment.', null=True, verbose_name='Notes')),
                ('invoice', models.ForeignKey(help_text='Invoice associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
