# Generated by Django 5.2.7 on 2025-10-25 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made the payment (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_deleted'], name='payments_is_dele_c5449e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_active'], name='payments_is_acti_308c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_deleted', 'is_active'], name='payments_is_dele_d80061_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date_created', 'is_deleted'], name='payments_date_cr_587273_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='payments_is_dele_78e8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='payments_date_cr_360c46_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payment_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='payment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_reference'], name='payment_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'status'], name='payment_method_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_date', 'currency'], name='payment_date_currency_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'is_deleted'], name='payment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('payment_reference',), name='unique_payment_reference'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_non_negative_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('invoice__isnull', True), _negated=True), name='payment_invoice_required'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('confirmed_at__isnull', False), _connector='OR'), name='payment_confirmed_at_required_for_completed'),
        ),
    ]
