# Generated by Django 5.2.7 on 2025-11-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Unique transaction ID from the payment processor or internal system.', max_length=100, null=True, unique=True, verbose_name='Payment Reference'),
        ),
    ]
