# Generated by Django 5.2.7 on 2025-11-23 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_is_primary_and_more'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(blank=True, help_text='Wishlist to which this item belongs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_items', to='wishlist.wishlist', verbose_name='Wishlist'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['is_deleted'], name='wishlists_is_dele_e6c5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['is_active'], name='wishlists_is_acti_bb6a48_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['is_deleted', 'is_active'], name='wishlists_is_dele_f984e6_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['date_created', 'is_deleted'], name='wishlists_date_cr_851925_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='wishlists_is_dele_bda3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='wishlists_date_cr_2df27d_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['is_deleted', 'is_active', 'product'], name='wishlist_it_is_dele_0ab031_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['is_deleted', 'is_active', 'variant'], name='wishlist_it_is_dele_82b443_idx'),
        ),
    ]
