# Generated by Django 5.2.7 on 2025-10-25 16:51

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('username', models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['email', 'role__role'],
            },
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('address_line_1', models.CharField(help_text='Street address, P.O. box, company name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province/Region (e.g., Massachusetts, Ontario, Bavaria)', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name (if applicable)', max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='VAT ID, GST number, etc.', max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, help_text='Full name for billing contact', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email for billing receipts', max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default billing address')),
                ('is_business', models.BooleanField(default=False, help_text='Business address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Addresses',
                'db_table': 'billing_addresses',
                'ordering': ['-is_default', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('address_line_1', models.CharField(help_text='Street address, P.O. box, company name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province/Region (e.g., Massachusetts, Ontario, Bavaria)', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default shipping address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'db_table': 'shipping_addresses',
                'ordering': ['-is_default', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='A profile image')),
                ('date_of_birth', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('newsletter_subscription', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('preferred_currency', models.CharField(default='USD', max_length=3)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('membership_tier', models.CharField(default='standard', max_length=20)),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50)),
                ('preferred_shipping_method', models.CharField(blank=True, max_length=50)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.billingaddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.shippingaddress')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('customer', 'Customer'), ('vendor', 'Vendor')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.userroles'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_deleted'], name='billing_add_is_dele_9b12c5_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_active'], name='billing_add_is_acti_5f6c85_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_deleted', 'is_active'], name='billing_add_is_dele_9b3654_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['date_created', 'is_deleted'], name='billing_add_date_cr_81473a_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='billing_add_is_dele_12b6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='billing_add_date_cr_f365a4_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['country', 'is_deleted'], name='billing_add_country_490469_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['city', 'is_deleted'], name='billing_add_city_7ec91f_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['state', 'is_deleted'], name='billing_add_state_286194_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['zip_code', 'is_deleted'], name='billing_add_zip_cod_897a31_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['country', 'state', 'city', 'is_deleted'], name='billing_add_country_d19849_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_deleted'], name='billing_add_user_id_b4f757_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_default', 'is_deleted'], name='billing_add_user_id_b70beb_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_business', 'is_deleted'], name='billing_add_user_id_edaa71_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_business', 'is_deleted'], name='billing_add_is_busi_b20d43_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['company_name', 'is_deleted'], name='billing_add_company_8b1156_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user',), name='unique_default_billing_address'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_deleted'], name='shipping_ad_is_dele_6d874a_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_active'], name='shipping_ad_is_acti_3614f3_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_deleted', 'is_active'], name='shipping_ad_is_dele_1d2619_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['date_created', 'is_deleted'], name='shipping_ad_date_cr_ebea3d_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='shipping_ad_is_dele_16d4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='shipping_ad_date_cr_6cbc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['country', 'is_deleted'], name='shipping_ad_country_361f25_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['city', 'is_deleted'], name='shipping_ad_city_27d716_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['state', 'is_deleted'], name='shipping_ad_state_80a863_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['zip_code', 'is_deleted'], name='shipping_ad_zip_cod_ac42e9_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['country', 'state', 'city', 'is_deleted'], name='shipping_ad_country_8b3488_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_deleted'], name='shipping_ad_user_id_07bf79_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_default', 'is_deleted'], name='shipping_ad_user_id_cc95d2_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'country', 'is_deleted'], name='shipping_ad_user_id_bf8f97_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_default', 'is_deleted'], name='shipping_ad_is_defa_c22166_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user',), name='unique_default_shipping_address'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted'], name='profiles_is_dele_eae219_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active'], name='profiles_is_acti_3d7a77_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'is_active'], name='profiles_is_dele_c5e454_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_created', 'is_deleted'], name='profiles_date_cr_d5a982_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='profiles_is_dele_34c340_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='profiles_date_cr_788785_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'is_deleted'], name='profiles_user_id_480975_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'user'], name='profiles_is_dele_971573_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number', 'is_deleted'], name='profiles_phone_n_b4faad_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'country'], name='profiles_is_dele_bbfe79_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'date_of_birth'], name='profiles_is_dele_935f02_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'newsletter_subscription'], name='profiles_is_dele_6ee91c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['shipping_address', 'is_deleted'], name='profiles_shippin_1f52ee_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['billing_address', 'is_deleted'], name='profiles_billing_4636ca_idx'),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['user', 'role', 'is_deleted'], name='user_roles_user_id_0e5b86_idx'),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['user', 'is_deleted'], name='user_roles_user_id_07a1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['role', 'is_deleted'], name='user_roles_role_4216e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='userroles',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'role'), name='unique_user_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='users_is_dele_21b557_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'is_active'], name='users_is_dele_399fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='users_is_dele_7b2969_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_id_7a277c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'email'], name='users_is_dele_68539a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'role'], name='users_is_dele_a06d44_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'is_staff'], name='users_is_dele_991703_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'is_superuser'], name='users_is_dele_1a118e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined', 'is_deleted'], name='users_date_jo_bb3bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login', 'is_deleted'], name='users_last_lo_ededd3_idx'),
        ),
    ]
