# Generated by Django 5.2.7 on 2025-10-11 20:08

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('username', models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['email'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True)),
                ('avatar', models.ImageField(default='profiles/profile_default.jpg', upload_to='profiles/', verbose_name='A profile image')),
                ('date_of_birth', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('newsletter_subscription', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('preferred_currency', models.CharField(default='USD', max_length=3)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('membership_tier', models.CharField(default='standard', max_length=20)),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50)),
                ('preferred_shipping_method', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
                'ordering': ['user__email'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uuid'], name='users_uuid_4cb658_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='users_is_dele_21b557_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_updated'], name='users_date_up_85e52a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_deleted'], name='users_is_acti_80025f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'date_updated'], name='users_is_acti_e34a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='users_is_dele_7b2969_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='users_first_n_0c5a67_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='users_last_na_5e9a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='users_date_jo_0c802f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login'], name='users_last_lo_65b80e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='users_email_a7cfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'is_active'], name='users_usernam_b4c624_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='users_first_n_de8b69_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'date_joined'], name='users_is_acti_33e113_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff', 'is_active'], name='users_is_staf_b59a17_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_superuser', 'is_active'], name='users_is_supe_fe365c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login', 'is_active'], name='users_last_lo_1eac82_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined', 'is_active'], name='users_date_jo_c97edd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined', 'is_active', 'is_deleted'], name='users_date_jo_a6bd02_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff', 'is_superuser', 'is_active'], name='users_is_staf_93212b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['uuid'], name='profiles_uuid_0a76d3_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active'], name='profiles_is_acti_3d7a77_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted'], name='profiles_is_dele_eae219_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_created'], name='profiles_date_cr_e1a416_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_updated'], name='profiles_date_up_21f9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active', 'is_deleted'], name='profiles_is_acti_30bc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_created', 'is_active'], name='profiles_date_cr_6ff089_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_active', 'date_updated'], name='profiles_is_acti_7caf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='profiles_is_dele_34c340_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='profiles_user_id_29277a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='profiles_gender_3ecb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country'], name='profiles_country_865c34_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_of_birth'], name='profiles_date_of_b6769c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number'], name='profiles_phone_n_a19d11_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'is_active'], name='profiles_user_id_1d8e68_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender', 'country'], name='profiles_gender_4acd38_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_of_birth', 'is_active'], name='profiles_date_of_38fdfa_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country', 'is_active'], name='profiles_country_281ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'is_active', 'is_deleted'], name='profiles_user_id_52e893_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number', 'is_active'], name='profiles_phone_n_b2591b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_of_birth', 'gender', 'country'], name='profiles_date_of_5abbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_created', 'country', 'is_active'], name='profiles_date_cr_7c4109_idx'),
        ),
    ]
