# Generated by Django 5.2.7 on 2025-10-25 19:26

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address_line_1',
            field=models.CharField(db_index=True, help_text='Street address, P.O. box, company name', max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, db_index=True, help_text='State/Province/Region (e.g., Massachusetts, Ontario, Bavaria)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zip_code',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line_1',
            field=models.CharField(db_index=True, help_text='Street address, P.O. box, company name', max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, db_index=True, help_text='State/Province/Region (e.g., Massachusetts, Ontario, Bavaria)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
