# Generated by Django 5.2.7 on 2025-11-23 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_billingaddress_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['is_deleted'], name='user_roles_is_dele_0717ce_idx'),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['is_active'], name='user_roles_is_acti_a67329_idx'),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['is_deleted', 'is_active'], name='user_roles_is_dele_783d61_idx'),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['date_created', 'is_deleted'], name='user_roles_date_cr_4d2b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='user_roles_is_dele_374cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='userroles',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='user_roles_date_cr_2a0f43_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user',), name='unique_user_profile'),
        ),
    ]
