# Generated by Django 5.2.7 on 2025-10-17 18:19

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('address_line_1', models.CharField(help_text='Street address, P.O. box, company name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province/Region (e.g., Massachusetts, Ontario, Bavaria)', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name (if applicable)', max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='VAT ID, GST number, etc.', max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, help_text='Full name for billing contact', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email for billing receipts', max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default billing address')),
                ('is_business', models.BooleanField(default=False, help_text='Business address')),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Addresses',
                'db_table': 'billing_addresses',
                'ordering': ['-is_default', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('address_line_1', models.CharField(help_text='Street address, P.O. box, company name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province/Region (e.g., Massachusetts, Ontario, Bavaria)', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default shipping address')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'db_table': 'shipping_addresses',
                'ordering': ['-is_default', '-date_created'],
            },
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_uuid_0a76d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_date_cr_e1a416_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_date_up_21f9e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_is_acti_30bc0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_date_cr_6ff089_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_is_acti_7caf4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_user_id_29277a_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_gender_3ecb8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_country_865c34_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_date_of_b6769c_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_phone_n_a19d11_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_user_id_1d8e68_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_gender_4acd38_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_date_of_38fdfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_country_281ee8_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_user_id_52e893_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_phone_n_b2591b_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_date_of_5abbdb_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_date_cr_7c4109_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_uuid_4cb658_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_date_up_85e52a_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_acti_80025f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_acti_e34a1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_usernam_baeb4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_first_n_0c5a67_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_last_na_5e9a3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_date_jo_0c802f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_last_lo_65b80e_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_a7cfd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_usernam_b4c624_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_first_n_de8b69_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_acti_33e113_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_staf_b59a17_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_supe_fe365c_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_last_lo_1eac82_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_date_jo_c97edd_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_date_jo_a6bd02_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_staf_93212b_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='A profile image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'is_active'], name='users_is_dele_399fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'email'], name='users_is_dele_68539a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'is_staff'], name='users_is_dele_991703_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'is_superuser'], name='users_is_dele_1a118e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined', 'is_deleted'], name='users_date_jo_bb3bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login', 'is_deleted'], name='users_last_lo_ededd3_idx'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.billingaddress'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.shippingaddress'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'is_active'], name='profiles_is_dele_c5e454_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_created', 'is_deleted'], name='profiles_date_cr_d5a982_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='profiles_date_cr_788785_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'is_deleted'], name='profiles_user_id_480975_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'user'], name='profiles_is_dele_971573_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number', 'is_deleted'], name='profiles_phone_n_b4faad_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'country'], name='profiles_is_dele_bbfe79_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'date_of_birth'], name='profiles_is_dele_935f02_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_deleted', 'newsletter_subscription'], name='profiles_is_dele_6ee91c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['shipping_address', 'is_deleted'], name='profiles_shippin_1f52ee_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['billing_address', 'is_deleted'], name='profiles_billing_4636ca_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_deleted'], name='billing_add_is_dele_9b12c5_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_active'], name='billing_add_is_acti_5f6c85_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_deleted', 'is_active'], name='billing_add_is_dele_9b3654_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['date_created', 'is_deleted'], name='billing_add_date_cr_81473a_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='billing_add_is_dele_12b6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='billing_add_date_cr_f365a4_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['country', 'is_deleted'], name='billing_add_country_490469_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['city', 'is_deleted'], name='billing_add_city_7ec91f_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['state', 'is_deleted'], name='billing_add_state_286194_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['zip_code', 'is_deleted'], name='billing_add_zip_cod_897a31_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['country', 'state', 'city', 'is_deleted'], name='billing_add_country_d19849_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_deleted'], name='billing_add_user_id_b4f757_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_default', 'is_deleted'], name='billing_add_user_id_b70beb_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_business', 'is_deleted'], name='billing_add_user_id_edaa71_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_business', 'is_deleted'], name='billing_add_is_busi_b20d43_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['company_name', 'is_deleted'], name='billing_add_company_8b1156_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user',), name='unique_default_billing_address'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_deleted'], name='shipping_ad_is_dele_6d874a_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_active'], name='shipping_ad_is_acti_3614f3_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_deleted', 'is_active'], name='shipping_ad_is_dele_1d2619_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['date_created', 'is_deleted'], name='shipping_ad_date_cr_ebea3d_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='shipping_ad_is_dele_16d4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='shipping_ad_date_cr_6cbc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['country', 'is_deleted'], name='shipping_ad_country_361f25_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['city', 'is_deleted'], name='shipping_ad_city_27d716_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['state', 'is_deleted'], name='shipping_ad_state_80a863_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['zip_code', 'is_deleted'], name='shipping_ad_zip_cod_ac42e9_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['country', 'state', 'city', 'is_deleted'], name='shipping_ad_country_8b3488_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_deleted'], name='shipping_ad_user_id_07bf79_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_default', 'is_deleted'], name='shipping_ad_user_id_cc95d2_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'country', 'is_deleted'], name='shipping_ad_user_id_bf8f97_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_default', 'is_deleted'], name='shipping_ad_is_defa_c22166_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user',), name='unique_default_shipping_address'),
        ),
    ]
