# Generated by Django 5.2.7 on 2025-10-28 15:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('invoice_number', models.CharField(help_text='Unique invoice number for external reference.', max_length=50, unique=True, verbose_name='Invoice Number')),
                ('issue_date', models.DateField(help_text='Date when the invoice was created.', verbose_name='Issue Date')),
                ('due_date', models.DateField(help_text='Date when the invoice is due for payment.', verbose_name='Due Date')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount billed in this invoice.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Amount')),
                ('currency', models.CharField(default='USD', help_text='Currency code in ISO 4217 format (e.g., USD, EUR, PLN).', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='DRAFT', help_text='Current status of this invoice.', max_length=20, verbose_name='Invoice Status')),
                ('notes', models.TextField(blank=True, help_text='Additional information or comments about the invoice.', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-date_created'],
            },
        ),
    ]
