# Generated by Django 5.2.7 on 2025-11-23 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The order this invoice is associated with.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['order', 'is_deleted'], name='invoice_order_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['order', 'status', 'is_deleted'], name='invoice_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date', 'is_deleted'], name='invoice_status_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date', 'due_date', 'status'], name='invoice_dates_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['total_amount', 'currency', 'is_deleted'], name='invoice_amount_currency_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['DRAFT', 'ISSUED', 'OVERDUE'])), fields=('order',), name='unique_active_order_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('order__isnull', True), models.Q(('status', 'DRAFT'), _negated=True), _connector='OR'), name='draft_invoice_must_have_no_order'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), ('order__isnull', False), _connector='OR'), name='paid_invoice_must_have_order'),
        ),
    ]
