# Generated by Django 5.2.7 on 2025-11-10 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_deleted'], name='billing_add_is_dele_9b12c5_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_active'], name='billing_add_is_acti_5f6c85_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_deleted', 'is_active'], name='billing_add_is_dele_9b3654_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['date_created', 'is_deleted'], name='billing_add_date_cr_81473a_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='billing_add_is_dele_12b6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='billing_add_date_cr_f365a4_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['country', 'is_deleted'], name='billing_add_country_490469_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['city', 'is_deleted'], name='billing_add_city_7ec91f_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['state', 'is_deleted'], name='billing_add_state_286194_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['zip_code', 'is_deleted'], name='billing_add_zip_cod_897a31_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['country', 'state', 'city', 'is_deleted'], name='billing_add_country_d19849_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_deleted'], name='billing_add_user_id_b4f757_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_default', 'is_deleted'], name='billing_add_user_id_b70beb_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_business', 'is_deleted'], name='billing_add_user_id_edaa71_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['is_business', 'is_deleted'], name='billing_add_is_busi_b20d43_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['company_name', 'is_deleted'], name='billing_add_company_8b1156_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user',), name='unique_default_billing_address'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_deleted'], name='shipping_ad_is_dele_6d874a_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_active'], name='shipping_ad_is_acti_3614f3_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_deleted', 'is_active'], name='shipping_ad_is_dele_1d2619_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['date_created', 'is_deleted'], name='shipping_ad_date_cr_ebea3d_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='shipping_ad_is_dele_16d4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='shipping_ad_date_cr_6cbc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['country', 'is_deleted'], name='shipping_ad_country_361f25_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['city', 'is_deleted'], name='shipping_ad_city_27d716_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['state', 'is_deleted'], name='shipping_ad_state_80a863_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['zip_code', 'is_deleted'], name='shipping_ad_zip_cod_ac42e9_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['country', 'state', 'city', 'is_deleted'], name='shipping_ad_country_8b3488_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_deleted'], name='shipping_ad_user_id_07bf79_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_default', 'is_deleted'], name='shipping_ad_user_id_cc95d2_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'country', 'is_deleted'], name='shipping_ad_user_id_bf8f97_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['is_default', 'is_deleted'], name='shipping_ad_is_defa_c22166_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user',), name='unique_default_shipping_address'),
        ),
    ]
