# Generated by Django 5.2.7 on 2025-11-23 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'ordering': ['-is_default', '-date_created'], 'verbose_name': 'Billing Address', 'verbose_name_plural': 'Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-is_default', '-date_created'], 'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.RemoveConstraint(
            model_name='billingaddress',
            name='unique_default_billing_address',
        ),
        migrations.RemoveConstraint(
            model_name='shippingaddress',
            name='unique_default_shipping_address',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('street__isnull', False), ('address_line_1__isnull', False), _connector='OR'), name='common_billingaddress_require_street_or_address_line', violation_error_message='Either street or address line 1 is required.'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('city__isnull', False), models.Q(('city', ''), _negated=True)), name='common_billingaddress_require_city', violation_error_message='City is required.'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('country__isnull', False), models.Q(('country', ''), _negated=True)), name='common_billingaddress_require_country', violation_error_message='Country is required.'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('zip_code__isnull', True), models.Q(('zip_code__isnull', False), models.Q(('zip_code', ''), _negated=True)), _connector='OR'), name='common_billingaddress_valid_zip_code', violation_error_message='ZIP code must be non-empty if provided.'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('is_business', True), models.Q(('is_business', False), ('contact_name__isnull', False), models.Q(('contact_name', ''), _negated=True)), _connector='OR'), name='common_billingaddress_require_contact_name', violation_error_message='Contact name is required for non-business addresses.'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True), ('email__contains', '@')), name='common_billingaddress_valid_email', violation_error_message='A valid email address is required.'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_business', True), _negated=True), models.Q(('is_business', True), ('tax_id__isnull', False), models.Q(('tax_id', ''), _negated=True)), _connector='OR'), name='common_billingaddress_require_tax_id_for_business', violation_error_message='Tax ID is required for business addresses.'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', True), ('phone__regex', '^\\+?[0-9\\s-]{5,20}$'), _connector='OR'), name='common_billingaddress_valid_phone', violation_error_message='Enter a valid phone number.'),
        ),
        migrations.AddConstraint(
            model_name='billingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', False), ('email__isnull', False), _connector='OR'), name='common_billingaddress_require_contact', violation_error_message='At least one contact method (phone or email) is required.'),
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('street__isnull', False), ('address_line_1__isnull', False), _connector='OR'), name='common_shippingaddress_require_street_or_address_line', violation_error_message='Either street or address line 1 is required.'),
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('city__isnull', False), models.Q(('city', ''), _negated=True)), name='common_shippingaddress_require_city', violation_error_message='City is required.'),
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('country__isnull', False), models.Q(('country', ''), _negated=True)), name='common_shippingaddress_require_country', violation_error_message='Country is required.'),
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.CheckConstraint(condition=models.Q(('zip_code__isnull', True), models.Q(('zip_code__isnull', False), models.Q(('zip_code', ''), _negated=True)), _connector='OR'), name='common_shippingaddress_valid_zip_code', violation_error_message='ZIP code must be non-empty if provided.'),
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user',), name='common_shippingaddress_single_default', violation_error_message='User can only have one default shipping address.'),
        ),
    ]
