# Generated by Django 5.2.7 on 2025-11-10 19:23

import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('quantity_available', models.PositiveIntegerField(db_index=True, default=0, help_text='Available quantity in units')),
                ('quantity_reserved', models.PositiveIntegerField(db_index=True, default=0, help_text='Reserved quantity in units')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Reorder level in units')),
                ('last_restocked', models.DateTimeField(blank=True, db_index=True, help_text='Last restocked date and time', null=True)),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='Last checked date and time')),
                ('is_backorder_allowed', models.BooleanField(db_index=True, default=False, help_text='Allow backorders for this inventory')),
                ('cost_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Cost price at this warehouse (can vary by location)', max_digits=10, null=True)),
                ('batch_number', models.CharField(blank=True, db_index=True, help_text='Batch number of this inventory', max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Expiry date of this inventory', null=True)),
                ('last_cost_update', models.DateTimeField(blank=True, db_index=True, help_text='Last cost update date and time', null=True)),
                ('manufacturing_cost_adjustment', models.DecimalField(blank=True, decimal_places=2, help_text='Additional manufacturing cost for this specific batch/location', max_digits=10, null=True)),
                ('packaging_cost_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Additional packaging cost for this specific batch/location', max_digits=8, null=True)),
                ('shipping_cost_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Additional shipping cost for this specific batch/location', max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventory',
                'ordering': ['warehouse', 'product_variant'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('address_line_1', models.CharField(db_index=True, help_text='Street address, P.O. box, company name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_index=True, help_text='State/Province/Region (e.g., Massachusetts, Ontario, Bavaria)', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, db_index=True, max_length=2, null=True)),
                ('name', models.CharField(db_index=True, help_text='Warehouse name', max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Warehouse code', max_length=50, unique=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Conatct phone of a warehouse', max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Conatct email of a warehouse', max_length=254, null=True)),
                ('is_operational', models.BooleanField(db_index=True, default=True, help_text='Is warehouse operational')),
                ('capacity', models.PositiveIntegerField(help_text='Total storage capacity in units')),
                ('warehouse_type', models.CharField(choices=[('main', 'Main'), ('regional', 'Regional'), ('store', 'Store'), ('drop_ship', 'Drop-ship')], db_index=True, default='regional', max_length=20)),
                ('operating_hours', models.JSONField(blank=True, help_text="Structured operating hours (e.g., {'mon': {'open': '09:00', 'close': '18:00'}})", null=True)),
                ('current_utilization', models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Current capacity utilization percentage', max_digits=5)),
                ('sla_days', models.PositiveIntegerField(db_index=True, default=2, help_text='Standard order processing time in days')),
                ('is_express_available', models.BooleanField(db_index=True, default=False, help_text='Whether express processing is available')),
                ('tax_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('currency', models.CharField(db_index=True, default='USD', max_length=3)),
                ('is_active_fulfillment', models.BooleanField(db_index=True, default=True, help_text='Whether this warehouse is active for order fulfillment')),
                ('max_order_per_day', models.PositiveIntegerField(default=1000, help_text='Maximum orders this warehouse can process per day')),
                ('timezone', models.CharField(default='UTC', help_text='Timezone of the warehouse location', max_length=50)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouses',
                'ordering': ['country', 'state', 'city', 'name'],
            },
        ),
    ]
