# Generated by Django 5.2.7 on 2025-11-10 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.warehouseprofile'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['is_deleted'], name='warehouses_is_dele_aca63f_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['is_active'], name='warehouses_is_acti_178fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['is_deleted', 'is_active'], name='warehouses_is_dele_fa018a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['date_created', 'is_deleted'], name='warehouses_date_cr_6548c2_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='warehouses_is_dele_dbdb35_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='warehouses_date_cr_81d0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['country', 'is_deleted'], name='warehouses_country_7dae9f_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['city', 'is_deleted'], name='warehouses_city_14cbc5_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['state', 'is_deleted'], name='warehouses_state_70c855_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['zip_code', 'is_deleted'], name='warehouses_zip_cod_a49c35_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['country', 'state', 'city', 'is_deleted'], name='warehouses_country_8ce5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['country', 'is_operational'], name='warehouses_country_025598_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['state', 'is_operational'], name='warehouses_state_89d12f_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['city', 'is_operational'], name='warehouses_city_c5f299_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['is_operational', 'is_active'], name='warehouses_is_oper_5507e2_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['warehouse_type', 'is_operational'], name='warehouses_warehou_3c655d_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['code', 'is_active'], name='warehouses_code_c92f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['name', 'is_operational'], name='warehouses_name_39db1e_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['current_utilization', 'is_operational'], name='warehouses_current_95a82a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['capacity', 'current_utilization'], name='warehouses_capacit_49ac9b_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['warehouse_type', 'current_utilization', 'is_operational'], name='warehouses_warehou_7e459a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['sla_days', 'is_operational'], name='warehouses_sla_day_3e6bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['is_express_available', 'is_operational'], name='warehouses_is_expr_195d26_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['warehouse_type', 'sla_days', 'is_operational'], name='warehouses_warehou_3213db_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['is_active_fulfillment', 'is_operational'], name='warehouses_is_acti_6ba5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['warehouse_type', 'is_active_fulfillment', 'is_operational'], name='warehouses_warehou_e388ac_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['country', 'is_active_fulfillment', 'is_operational'], name='warehouses_country_f01038_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['country', 'state', 'is_operational'], name='warehouses_country_557cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['warehouse_type', 'country', 'is_active'], name='warehouses_warehou_56222e_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['country', 'city', 'is_operational'], name='warehouses_country_9815e5_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['state', 'city', 'is_operational'], name='warehouses_state_2989a6_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['warehouse_type', 'is_operational', 'is_active_fulfillment'], name='warehouses_warehou_77925e_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['manager', 'is_operational'], name='warehouses_manager_1fb04f_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['is_operational', 'is_active', 'is_active_fulfillment'], name='warehouses_is_oper_5abac0_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['country', 'state', 'city', 'is_operational'], name='warehouses_country_d02f90_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['id', 'is_operational', 'is_active'], name='warehouses_id_9517c0_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseprofile',
            index=models.Index(fields=['code', 'is_operational', 'is_active'], name='warehouses_code_f3378a_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'country'), name='unique_warehouse_name_country'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_warehouse_code'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='warehouse_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('contact_phone__isnull', False), ('contact_email__isnull', False), _connector='OR'), name='at_least_one_contact_method'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('current_utilization__gte', 0), ('current_utilization__lte', 100)), name='valid_utilization_range'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('sla_days__gt', 0)), name='positive_sla_days'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_order_per_day__gt', 0)), name='positive_max_orders'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('is_active_fulfillment', False), ('is_operational', True), _connector='OR'), name='fulfillment_requires_operational'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.CheckConstraint(condition=models.Q(('manager__isnull', True), ('is_operational', True), _connector='OR'), name='manager_requires_operational'),
        ),
        migrations.AddConstraint(
            model_name='warehouseprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('warehouse_type', 'main'), _negated=True), ('is_operational', True), _connector='OR'), name='main_warehouse_must_be_operational'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['is_deleted'], name='inventory_is_dele_f15209_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['is_active'], name='inventory_is_acti_3b2601_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['is_deleted', 'is_active'], name='inventory_is_dele_b14c60_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['date_created', 'is_deleted'], name='inventory_date_cr_19332d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='inventory_is_dele_420aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='inventory_date_cr_6b8d56_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_variant', 'warehouse', 'is_deleted'], name='inventory_product_0128ca_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'product_variant', 'is_deleted'], name='inventory_warehou_42cf8d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_variant', 'warehouse', 'is_active', 'is_deleted'], name='inventory_product_425c55_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity_available', 'is_active'], name='inventory_quantit_f8ac80_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'quantity_available', 'is_active'], name='inventory_warehou_8f522e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_variant', 'quantity_available', 'is_active'], name='inventory_product_d2eaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity_available', 'quantity_reserved', 'is_active'], name='inventory_quantit_ed5ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity_available', 'reorder_level', 'is_active'], name='inventory_quantit_533b46_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'quantity_available', 'reorder_level', 'is_active'], name='inventory_warehou_067e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_variant', 'quantity_available', 'reorder_level', 'is_active'], name='inventory_product_9e44b8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['last_restocked', 'is_active'], name='inventory_last_re_782dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'last_restocked', 'is_active'], name='inventory_warehou_2a58d5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['last_restocked', 'quantity_available', 'is_active'], name='inventory_last_re_685b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['is_backorder_allowed', 'quantity_available', 'is_active'], name='inventory_is_back_85eb71_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'is_backorder_allowed', 'is_active'], name='inventory_warehou_e488d0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['expiry_date', 'is_active'], name='inventory_expiry__eea63d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'expiry_date', 'is_active'], name='inventory_warehou_e2ba07_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_variant', 'expiry_date', 'is_active'], name='inventory_product_aba60f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['expiry_date', 'quantity_available', 'is_active'], name='inventory_expiry__8246e1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['batch_number', 'is_active'], name='inventory_batch_n_c708c4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'batch_number', 'is_active'], name='inventory_warehou_4c065a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['cost_price', 'is_active'], name='inventory_cost_pr_0381a4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'cost_price', 'is_active'], name='inventory_warehou_616023_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'is_active', 'date_created'], name='inventory_warehou_6a3047_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_variant', 'is_active', 'date_created'], name='inventory_product_3ae430_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['is_active', 'quantity_available', 'date_created'], name='inventory_is_acti_b4f6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'product_variant', 'date_created', 'is_active'], name='inventory_warehou_dfa059_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_variant', 'is_deleted', 'is_active'], name='inventory_product_0a5039_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'is_deleted', 'is_active'], name='inventory_warehou_0b38d4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product_variant', 'warehouse', 'is_deleted', 'is_active'], name='inventory_product_fa704c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['last_checked', 'is_active'], name='inventory_last_ch_5ed77e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'last_checked', 'is_active'], name='inventory_warehou_121764_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('manufacturing_cost_adjustment__isnull', True), ('manufacturing_cost_adjustment__gte', 0), _connector='OR'), name='non_negative_mfg_adjustment'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('packaging_cost_adjustment__isnull', True), ('packaging_cost_adjustment__gte', 0), _connector='OR'), name='non_negative_packaging_adjustment'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_cost_adjustment__isnull', True), ('shipping_cost_adjustment__gte', 0), _connector='OR'), name='non_negative_shipping_adjustment'),
        ),
    ]
