# Generated by Django 5.2.7 on 2025-11-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
        ('products', '0002_productimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='products.productvariant'),
        ),
    ]
