# Generated by Django 5.2.7 on 2025-10-28 15:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Product rating (0.00–5.00).', max_digits=3)),
                ('title', models.CharField(blank=True, help_text='Optional title for the review.', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Detailed review text.')),
                ('product', models.ForeignKey(help_text='The product this review refers to.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'product_reviews',
                'ordering': ['-date_created', '-rating'],
            },
        ),
    ]
