# Generated by Django 5.2.7 on 2025-10-25 16:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='The user who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_deleted'], name='reviews_rev_is_dele_b82a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_active'], name='reviews_rev_is_acti_dd6f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_deleted', 'is_active'], name='reviews_rev_is_dele_7eda9a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['date_created', 'is_deleted'], name='reviews_rev_date_cr_717cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='reviews_rev_is_dele_aebaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='reviews_rev_date_cr_db1e75_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'rating'], name='review_product_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'product'], name='review_user_product_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_deleted', 'rating'], name='review_deleted_rating_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', Decimal('0.00')), ('rating__lte', Decimal('5.00'))), name='review_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'product'), name='unique_active_review_per_user_product'),
        ),
    ]
