# Generated by Django 5.2.7 on 2025-10-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='product_rev_is_dele_469f29_idx',
            old_name='reviews_rev_is_dele_b82a8d_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='product_rev_is_acti_feede9_idx',
            old_name='reviews_rev_is_acti_dd6f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='product_rev_is_dele_3ab428_idx',
            old_name='reviews_rev_is_dele_7eda9a_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='product_rev_date_cr_b5522b_idx',
            old_name='reviews_rev_date_cr_717cfa_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='product_rev_is_dele_7e6219_idx',
            old_name='reviews_rev_is_dele_aebaf8_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='product_rev_date_cr_fd9611_idx',
            old_name='reviews_rev_date_cr_db1e75_idx',
        ),
        migrations.AlterModelTable(
            name='review',
            table='product_reviews',
        ),
    ]
