# Generated by Django 5.2.7 on 2025-10-17 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('coupon_code', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_amount', models.PositiveIntegerField(default=100, help_text='Discount in %(s)')),
                ('minimum_amount', models.PositiveIntegerField(default=500, help_text='Minimum amount required to use this coupon')),
                ('expiration_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=1, help_text='Number of times this coupon can be used')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
                'ordering': ['-expiration_date'],
                'indexes': [models.Index(fields=['is_deleted'], name='coupons_is_dele_93fec4_idx'), models.Index(fields=['is_active'], name='coupons_is_acti_dbb3f6_idx'), models.Index(fields=['is_deleted', 'is_active'], name='coupons_is_dele_04fbcc_idx'), models.Index(fields=['date_created', 'is_deleted'], name='coupons_date_cr_16afb9_idx'), models.Index(fields=['is_deleted', 'date_deleted'], name='coupons_is_dele_28fc8c_idx'), models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='coupons_date_cr_14a29e_idx'), models.Index(fields=['is_deleted', 'is_expired'], name='coupons_is_dele_8ed3be_idx'), models.Index(fields=['coupon_code', 'is_deleted', 'is_expired'], name='coupons_coupon__b62de7_idx'), models.Index(fields=['expiration_date', 'is_deleted', 'is_expired'], name='coupons_expirat_0605f5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('coupon_code',), name='unique_coupon_code'), models.CheckConstraint(condition=models.Q(('usage_limit__gte', 1)), name='usage_limit_check')],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('status', models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.coupon')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of the product', max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Selected variant for this cart item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_items',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['cart', 'is_deleted'], name='cart_items_cart_id_855420_idx'), models.Index(fields=['cart', 'product', 'is_deleted'], name='cart_items_cart_id_49b06a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted'], name='carts_is_dele_99cda1_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_active'], name='carts_is_acti_b2c2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted', 'is_active'], name='carts_is_dele_c44fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['date_created', 'is_deleted'], name='carts_date_cr_a3e272_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='carts_is_dele_0a8c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='carts_date_cr_2f4564_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status'], name='carts_status_9d207c_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted', 'status'], name='carts_is_dele_2c2b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_deleted', 'status'], name='carts_user_id_2abb25_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['date_created', 'is_deleted', 'status'], name='carts_date_cr_6c2587_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'date_created'], name='carts_status_1ff2ed_idx'),
        ),
    ]
