# Generated by Django 5.2.7 on 2025-11-10 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected variant for this cart item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_deleted'], name='coupons_is_dele_93fec4_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupons_is_acti_dbb3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_deleted', 'is_active'], name='coupons_is_dele_04fbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['date_created', 'is_deleted'], name='coupons_date_cr_16afb9_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='coupons_is_dele_28fc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='coupons_date_cr_14a29e_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_deleted', 'is_expired'], name='coupons_is_dele_8ed3be_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_code', 'is_deleted', 'is_expired'], name='coupons_coupon__b62de7_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['expiration_date', 'is_deleted', 'is_expired'], name='coupons_expirat_0605f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('coupon_code',), name='unique_coupon_code'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('usage_limit__gte', 1)), name='usage_limit_check'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.coupon'),
        ),
        migrations.AddField(
            model_name='savedcart',
            name='original_cart',
            field=models.ForeignKey(blank=True, help_text='Original cart that was saved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_versions', to='cart.cart', verbose_name='Original Cart'),
        ),
        migrations.AddField(
            model_name='savedcart',
            name='user',
            field=models.ForeignKey(help_text='User who saved this cart', on_delete=django.db.models.deletion.PROTECT, related_name='saved_carts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='savedcartitem',
            name='product',
            field=models.ForeignKey(help_text='Product in the saved cart', on_delete=django.db.models.deletion.PROTECT, related_name='saved_cart_items', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='savedcartitem',
            name='saved_cart',
            field=models.ForeignKey(help_text='Saved cart containing this item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.savedcart', verbose_name='Saved Cart'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['is_deleted'], name='cart_items_is_dele_c444fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['is_active'], name='cart_items_is_acti_69ac6f_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['is_deleted', 'is_active'], name='cart_items_is_dele_1badeb_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['date_created', 'is_deleted'], name='cart_items_date_cr_f308a9_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='cart_items_is_dele_408ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='cart_items_date_cr_8985ca_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'is_deleted'], name='cart_items_cart_id_855420_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product', 'is_deleted'], name='cart_items_cart_id_49b06a_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product', 'is_deleted'], name='cart_items_product_c36f50_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cart', 'product'), name='unique_active_product_per_cart'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted'], name='carts_is_dele_99cda1_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_active'], name='carts_is_acti_b2c2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted', 'is_active'], name='carts_is_dele_c44fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['date_created', 'is_deleted'], name='carts_date_cr_a3e272_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='carts_is_dele_0a8c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='carts_date_cr_2f4564_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status'], name='carts_status_9d207c_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted', 'status'], name='carts_is_dele_2c2b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_deleted', 'status'], name='carts_user_id_2abb25_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['date_created', 'is_deleted', 'status'], name='carts_date_cr_6c2587_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'date_created'], name='carts_status_1ff2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['user', 'is_deleted', 'is_active'], name='saved_carts_user_id_5afd43_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['user', 'is_default'], name='saved_carts_user_id_f350c6_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['user', 'date_created'], name='saved_carts_user_id_60feec_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['expires_at', 'is_deleted'], name='saved_carts_expires_a7b8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['is_deleted', 'expires_at'], name='saved_carts_is_dele_8d16e2_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['is_active', 'is_deleted', 'date_created'], name='saved_carts_is_acti_6062b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedcart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user', 'is_default'), name='unique_default_cart_per_active_user'),
        ),
        migrations.AddConstraint(
            model_name='savedcart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'name'), name='unique_cart_name_per_active_user'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['saved_cart', 'is_deleted'], name='saved_cart__saved_c_69cf98_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['product', 'is_deleted'], name='saved_cart__product_ae692c_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['price'], name='saved_cart__price_22806e_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['quantity'], name='saved_cart__quantit_315694_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['saved_cart', 'is_active', 'is_deleted'], name='saved_cart__saved_c_e95dbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedcartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('saved_cart', 'product'), name='unique_product_per_active_saved_cart'),
        ),
    ]
