# Generated by Django 5.2.7 on 2025-10-25 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected variant for this cart item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_deleted'], name='coupons_is_dele_93fec4_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupons_is_acti_dbb3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_deleted', 'is_active'], name='coupons_is_dele_04fbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['date_created', 'is_deleted'], name='coupons_date_cr_16afb9_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='coupons_is_dele_28fc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='coupons_date_cr_14a29e_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_deleted', 'is_expired'], name='coupons_is_dele_8ed3be_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_code', 'is_deleted', 'is_expired'], name='coupons_coupon__b62de7_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['expiration_date', 'is_deleted', 'is_expired'], name='coupons_expirat_0605f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('coupon_code',), name='unique_coupon_code'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('usage_limit__gte', 1)), name='usage_limit_check'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.coupon'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'is_deleted'], name='cart_items_cart_id_855420_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product', 'is_deleted'], name='cart_items_cart_id_49b06a_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted'], name='carts_is_dele_99cda1_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_active'], name='carts_is_acti_b2c2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted', 'is_active'], name='carts_is_dele_c44fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['date_created', 'is_deleted'], name='carts_date_cr_a3e272_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='carts_is_dele_0a8c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='carts_date_cr_2f4564_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status'], name='carts_status_9d207c_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_deleted', 'status'], name='carts_is_dele_2c2b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_deleted', 'status'], name='carts_user_id_2abb25_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['date_created', 'is_deleted', 'status'], name='carts_date_cr_6c2587_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'date_created'], name='carts_status_1ff2ed_idx'),
        ),
    ]
