# Generated by Django 5.2.7 on 2025-11-23 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('products', '0002_productimage_is_primary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedcart',
            name='unique_default_cart_per_active_user',
        ),
        migrations.RemoveConstraint(
            model_name='savedcart',
            name='unique_cart_name_per_active_user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product this coupon applies to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Coupon Code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.PositiveIntegerField(default=100, help_text='Discount percentage', verbose_name='Discount Amount (%)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(db_index=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Expired'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.PositiveIntegerField(default=500, help_text='Minimum cart amount required to use this coupon', verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of times this coupon can be used', verbose_name='Usage Limit'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used', verbose_name='Used Count'),
        ),
        migrations.AlterField(
            model_name='savedcartitem',
            name='saved_cart',
            field=models.ForeignKey(help_text='Saved cart containing this item', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cart.savedcart', verbose_name='Saved Cart'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['product', 'is_deleted', 'is_expired'], name='coupons_product_72de67_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['minimum_amount', 'is_deleted'], name='coupons_minimum_1d740e_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['used_count', 'usage_limit'], name='coupons_used_co_b10b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['is_deleted'], name='saved_carts_is_dele_758293_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['is_active'], name='saved_carts_is_acti_3b8299_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['is_deleted', 'is_active'], name='saved_carts_is_dele_0314a0_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['date_created', 'is_deleted'], name='saved_carts_date_cr_3b8e35_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='saved_carts_is_dele_e2ea11_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcart',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='saved_carts_date_cr_397846_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['is_deleted'], name='saved_cart__is_dele_fb15ce_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['is_active'], name='saved_cart__is_acti_c11868_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['is_deleted', 'is_active'], name='saved_cart__is_dele_6e5def_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['date_created', 'is_deleted'], name='saved_cart__date_cr_e9a85a_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='saved_cart__is_dele_b21e53_idx'),
        ),
        migrations.AddIndex(
            model_name='savedcartitem',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='saved_cart__date_cr_f6ee4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gt', 0), ('discount_amount__lte', 100)), name='valid_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('expiration_date__gt', models.F('date_created')), ('expiration_date__isnull', True), _connector='OR'), name='valid_expiration_date'),
        ),
        migrations.AddConstraint(
            model_name='savedcart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('user',), name='unique_default_saved_cart_per_user', violation_error_message='User can only have one default saved cart.'),
        ),
        migrations.AddConstraint(
            model_name='savedcart',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', True), models.Q(('name', ''), _negated=True), _connector='OR'), name='saved_cart_name_required', violation_error_message='Name is required for non-default saved carts.'),
        ),
    ]
