# Generated by Django 5.2.7 on 2025-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_savedcart_unique_default_cart_per_active_user_and_more'),
        ('products', '0002_productimage_is_primary_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='coupons_minimum_f4bb1a_idx',
            old_name='coupons_minimum_1d740e_idx',
        ),
        migrations.AddField(
            model_name='coupon',
            name='label',
            field=models.CharField(blank=True, db_index=True, help_text='Label for this coupon', max_length=50, null=True, verbose_name='Label'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['label', 'is_expired'], name='coupons_label_72e44c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['label', 'is_deleted', 'is_expired'], name='coupons_label_84c676_idx'),
        ),
    ]
