# Generated by Django 5.2.7 on 2025-10-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingclass',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_classes', to='users.shippingaddress'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['is_deleted'], name='shipping_cl_is_dele_7b057f_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['is_active'], name='shipping_cl_is_acti_33fbea_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['is_deleted', 'is_active'], name='shipping_cl_is_dele_599bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['date_created', 'is_deleted'], name='shipping_cl_date_cr_dd1c67_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='shipping_cl_is_dele_790288_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='shipping_cl_date_cr_5b7310_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['order', 'is_deleted', 'is_active'], name='shipping_cl_order_i_8d40b3_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['shipping_address', 'is_deleted', 'is_active'], name='shipping_cl_shippin_03b226_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['shipping_type', 'is_deleted', 'is_active'], name='shipping_cl_shippin_453f74_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['carrier_type', 'is_deleted', 'is_active'], name='shipping_cl_carrier_753ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['free_shipping_threshold', 'is_deleted', 'is_active'], name='shipping_cl_free_sh_9989da_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['domestic_only', 'is_active', 'is_deleted'], name='shipping_cl_domesti_8d3d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingclass',
            index=models.Index(fields=['shipping_type', 'carrier_type', 'is_active', 'is_deleted'], name='shipping_cl_shippin_676bfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingclass',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_days_min__lte', models.F('estimated_days_max'))), name='valid_estimated_days_range'),
        ),
        migrations.AddConstraint(
            model_name='shippingclass',
            constraint=models.CheckConstraint(condition=models.Q(('base_cost__gt', 0)), name='non_negative_greater_than_zero_base_cost'),
        ),
        migrations.AddConstraint(
            model_name='shippingclass',
            constraint=models.CheckConstraint(condition=models.Q(('max_weight_kg__gt', 0)), name='non_negative_greater_than_zero_max_weight_kg'),
        ),
        migrations.AddConstraint(
            model_name='shippingclass',
            constraint=models.CheckConstraint(condition=models.Q(('insurance_cost__gte', 0)), name='non_negative_insurance_cost'),
        ),
        migrations.AddConstraint(
            model_name='shippingclass',
            constraint=models.CheckConstraint(condition=models.Q(('free_shipping_threshold__gte', 0)), name='non_negative_free_shipping_threshold'),
        ),
    ]
