# Generated by Django 5.2.7 on 2025-10-25 19:26

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('address_line_1', models.CharField(db_index=True, help_text='Street address, P.O. box, company name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_index=True, help_text='State/Province/Region (e.g., Massachusetts, Ontario, Bavaria)', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, db_index=True, max_length=2, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_operational', models.BooleanField(db_index=True, default=True)),
                ('capacity', models.PositiveIntegerField(help_text='Total storage capacity in units')),
                ('warehouse_type', models.CharField(choices=[('main', 'Main'), ('regional', 'Regional'), ('store', 'Store'), ('drop_ship', 'Drop-ship')], db_index=True, default='regional', max_length=20)),
                ('operating_hours', models.JSONField(blank=True, help_text="Structured operating hours (e.g., {'mon': {'open': '09:00', 'close': '18:00'}})", null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['country', 'state', 'city', 'name'],
                'indexes': [models.Index(fields=['is_deleted'], name='warehouses_is_dele_aca63f_idx'), models.Index(fields=['is_active'], name='warehouses_is_acti_178fdd_idx'), models.Index(fields=['is_deleted', 'is_active'], name='warehouses_is_dele_fa018a_idx'), models.Index(fields=['date_created', 'is_deleted'], name='warehouses_date_cr_6548c2_idx'), models.Index(fields=['is_deleted', 'date_deleted'], name='warehouses_is_dele_dbdb35_idx'), models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='warehouses_date_cr_81d0fc_idx'), models.Index(fields=['country', 'is_deleted'], name='warehouses_country_7dae9f_idx'), models.Index(fields=['city', 'is_deleted'], name='warehouses_city_14cbc5_idx'), models.Index(fields=['state', 'is_deleted'], name='warehouses_state_70c855_idx'), models.Index(fields=['zip_code', 'is_deleted'], name='warehouses_zip_cod_a49c35_idx'), models.Index(fields=['country', 'state', 'city', 'is_deleted'], name='warehouses_country_8ce5fa_idx'), models.Index(fields=['country', 'is_operational'], name='warehouses_country_025598_idx'), models.Index(fields=['state', 'is_operational'], name='warehouses_state_89d12f_idx'), models.Index(fields=['city', 'is_operational'], name='warehouses_city_c5f299_idx'), models.Index(fields=['is_operational', 'is_active'], name='warehouses_is_oper_5507e2_idx'), models.Index(fields=['warehouse_type', 'is_operational'], name='warehouses_warehou_3c655d_idx'), models.Index(fields=['code', 'is_active'], name='warehouses_code_c92f3a_idx'), models.Index(fields=['country', 'state', 'is_operational'], name='warehouses_country_557cbe_idx'), models.Index(fields=['warehouse_type', 'country', 'is_active'], name='warehouses_warehou_56222e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'country'), name='unique_warehouse_name_country'), models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='warehouse_capacity_positive'), models.CheckConstraint(condition=models.Q(('contact_phone__isnull', False), ('contact_email__isnull', False), _connector='OR'), name='at_least_one_contact_method')],
            },
        ),
    ]
