# Generated by Django 5.2.7 on 2025-10-17 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current order status (e.g., pending, shipped, completed)', max_length=20, verbose_name='Order Status')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.cart', verbose_name='Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of the product', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Selected variant for this cart item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('name', models.CharField(help_text='Tax name', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate (0–1)', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Base taxable amount', max_digits=12)),
                ('amount_with_taxes', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Amount including taxes', max_digits=12, null=True)),
                ('tax_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount only (amount * rate)', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_taxes', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Tax',
                'verbose_name_plural': 'Order Taxes',
                'db_table': 'order_taxes',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted'], name='orders_is_dele_e957f6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_active'], name='orders_is_acti_86936c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted', 'is_active'], name='orders_is_dele_93468a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_created', 'is_deleted'], name='orders_date_cr_e57932_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='orders_is_dele_cf4cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='orders_date_cr_df2dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'is_deleted'], name='orders_user_id_eb8f09_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cart', 'is_deleted'], name='orders_cart_id_c19ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'is_deleted'], name='orders_status_f648fe_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_amount', 'is_deleted'], name='orders_total_a_474ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'is_deleted'], name='orders_user_id_01a675_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'date_created', 'is_deleted'], name='orders_status_f9cc26_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['is_deleted', 'is_active', 'product'], name='order_items_is_dele_1f97c0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['is_deleted', 'is_active', 'variant'], name='order_items_is_dele_902a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'is_deleted'], name='order_items_order_i_8d4821_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product', 'is_deleted'], name='order_items_order_i_8b0709_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['is_deleted'], name='order_taxes_is_dele_45c6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['is_active'], name='order_taxes_is_acti_8d071a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['is_deleted', 'is_active'], name='order_taxes_is_dele_c51ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['date_created', 'is_deleted'], name='order_taxes_date_cr_cfe3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='order_taxes_is_dele_437f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='order_taxes_date_cr_9316ae_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['order', 'is_deleted'], name='order_taxes_order_i_c80134_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['order', 'name', 'is_deleted'], name='order_taxes_order_i_b1a03a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['order', 'rate', 'is_deleted'], name='order_taxes_order_i_7708da_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordertax',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('order', 'name'), name='unique_order_tax_name'),
        ),
        migrations.AddConstraint(
            model_name='ordertax',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 1)), name='valid_order_tax_rate'),
        ),
        migrations.AddConstraint(
            model_name='ordertax',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='valid_order_tax_amount'),
        ),
        migrations.AddConstraint(
            model_name='ordertax',
            constraint=models.CheckConstraint(condition=models.Q(('amount_with_taxes__gte', 0)), name='valid_order_tax_amount_with_taxes'),
        ),
    ]
