# Generated by Django 5.2.7 on 2025-10-18 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected variant for this cart item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='ordertax',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_taxes', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted'], name='orders_is_dele_e957f6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_active'], name='orders_is_acti_86936c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted', 'is_active'], name='orders_is_dele_93468a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_created', 'is_deleted'], name='orders_date_cr_e57932_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='orders_is_dele_cf4cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='orders_date_cr_df2dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'is_deleted'], name='orders_user_id_eb8f09_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cart', 'is_deleted'], name='orders_cart_id_c19ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'is_deleted'], name='orders_status_f648fe_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_amount', 'is_deleted'], name='orders_total_a_474ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'is_deleted'], name='orders_user_id_01a675_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'date_created', 'is_deleted'], name='orders_status_f9cc26_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['is_deleted', 'is_active', 'product'], name='order_items_is_dele_1f97c0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['is_deleted', 'is_active', 'variant'], name='order_items_is_dele_902a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'is_deleted'], name='order_items_order_i_8d4821_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product', 'is_deleted'], name='order_items_order_i_8b0709_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['is_deleted'], name='order_taxes_is_dele_45c6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['is_active'], name='order_taxes_is_acti_8d071a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['is_deleted', 'is_active'], name='order_taxes_is_dele_c51ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['date_created', 'is_deleted'], name='order_taxes_date_cr_cfe3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['is_deleted', 'date_deleted'], name='order_taxes_is_dele_437f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['date_created', 'is_active', 'is_deleted'], name='order_taxes_date_cr_9316ae_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['order', 'is_deleted'], name='order_taxes_order_i_c80134_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['order', 'name', 'is_deleted'], name='order_taxes_order_i_b1a03a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertax',
            index=models.Index(fields=['order', 'rate', 'is_deleted'], name='order_taxes_order_i_7708da_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordertax',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('order', 'name'), name='unique_order_tax_name'),
        ),
        migrations.AddConstraint(
            model_name='ordertax',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 1)), name='valid_order_tax_rate'),
        ),
        migrations.AddConstraint(
            model_name='ordertax',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='valid_order_tax_amount'),
        ),
        migrations.AddConstraint(
            model_name='ordertax',
            constraint=models.CheckConstraint(condition=models.Q(('amount_with_taxes__gte', 0)), name='valid_order_tax_amount_with_taxes'),
        ),
    ]
