# Generated by Django 5.2.7 on 2025-11-23 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_savedcart_unique_default_cart_per_active_user_and_more'),
        ('common', '0003_alter_billingaddress_options_and_more'),
        ('orders', '0002_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Current order status (e.g., pending, shipped, completed)', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('completed', 'Completed')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='orders_order_positive_total_amount', violation_error_message='Total amount cannot be negative.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('order_number__isnull', False)), fields=('order_number',), name='orders_order_unique_order_number', violation_error_message='Order number must be unique.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['completed', 'cancelled', 'refunded']), _negated=True), models.Q(('status__in', ['completed', 'cancelled', 'refunded']), ('is_active', True), ('is_deleted', False)), _connector='OR'), name='orders_order_protect_completed_orders', violation_error_message='Completed, cancelled, or refunded orders cannot be modified.'),
        ),
        migrations.AddConstraint(
            model_name='orderstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'approved', 'processing', 'paid', 'unpaid', 'shipped', 'delivered', 'cancelled', 'refunded', 'completed'))), name='orders_orderstatushistory_valid_status', violation_error_message='Invalid status value.'),
        ),
        migrations.AddConstraint(
            model_name='orderstatushistory',
            constraint=models.UniqueConstraint(fields=('order', 'status', 'date_created'), name='orders_orderstatushistory_unique_status_per_timestamp', violation_error_message='Duplicate status change detected.'),
        ),
    ]
