# Generated by Django 5.2.7 on 2025-11-23 13:41

import common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_categories_slug_b4303a_idx'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Set as the main product image (only one image can be primary)', verbose_name='Primary Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Original price before discount. Used to show the 'was' price when the product is on sale.", max_digits=10, null=True, verbose_name='Compare At Price'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility and SEO (recommended: max 125 characters)', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Alt Text'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which images are displayed (lower numbers first)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Upload a high-quality product image (recommended size: 800x800px, max 5MB)', upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), common.validators.FileSizeValidator(5242880)], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='The product this image belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_primary'], name='product_ima_is_prim_873e82_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('product', 'is_primary'), name='unique_primary_image_per_product'),
        ),
    ]
